include:
  - board: ble_micro_pro
    shield: palmslave_left
    snippet: studio-rpc-usb-uart
    artifact-name: palmslave_left
  - board: ble_micro_pro
    shield: palmslave_right
    snippet: studio-rpc-usb-uart
    artifact-name: palmslave_right
  - board: ble_micro_pro
    shield: settings_reset